Update lighthouse_dynamic.yml

diff --git a/.github/workflows/lighthouse_dynamic.yml b/.github/workflows/lighthouse_dynamic.yml
--- a/.github/workflows/lighthouse_dynamic.yml
+++ b/.github/workflows/lighthouse_dynamic.yml
@@ -40,4 +40,12 @@ jobs:
           }' > lighthouserc.json
 
       - name: Run Lighthouse CI
-        run: lhci autorun
+        run: |
+          lhci autorun || echo "LHCI failed"
+      
+          echo "========== Public Report Link =========="
+          cat .lighthouseci/.lighthouseci/upload-report.json | jq -r '.[].url'
+      
+          echo "========== Full Lighthouse Report JSON =========="
+          cat .lighthouseci/*report.json
+
